################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Src/lvgl/demos/benchmark/assets \
Core/Src/lvgl/demos/benchmark \
Core/Src/lvgl/demos/keypad_encoder \
Core/Src/lvgl/demos \
Core/Src/lvgl/demos/music/assets \
Core/Src/lvgl/demos/music \
Core/Src/lvgl/demos/render/assets \
Core/Src/lvgl/demos/render \
Core/Src/lvgl/demos/stress \
Core/Src/lvgl/demos/vector_graphic/assets \
Core/Src/lvgl/demos/vector_graphic \
Core/Src/lvgl/demos/widgets/assets \
Core/Src/lvgl/demos/widgets \
Core/Src/lvgl/env_support/pikascript \
Core/Src/lvgl/env_support/rt-thread \
Core/Src/lvgl/env_support/rt-thread/squareline \
Core/Src/lvgl/examples/anim \
Core/Src/lvgl/examples/assets \
Core/Src/lvgl/examples/assets/emoji \
Core/Src/lvgl/examples/event \
Core/Src/lvgl/examples/get_started \
Core/Src/lvgl/examples/grad \
Core/Src/lvgl/examples/layouts/flex \
Core/Src/lvgl/examples/layouts/grid \
Core/Src/lvgl/examples/libs/barcode \
Core/Src/lvgl/examples/libs/bmp \
Core/Src/lvgl/examples/libs/ffmpeg \
Core/Src/lvgl/examples/libs/freetype \
Core/Src/lvgl/examples/libs/gif \
Core/Src/lvgl/examples/libs/libjpeg_turbo \
Core/Src/lvgl/examples/libs/libpng \
Core/Src/lvgl/examples/libs/lodepng \
Core/Src/lvgl/examples/libs/qrcode \
Core/Src/lvgl/examples/libs/rlottie \
Core/Src/lvgl/examples/libs/svg \
Core/Src/lvgl/examples/libs/tiny_ttf \
Core/Src/lvgl/examples/libs/tjpgd \
Core/Src/lvgl/examples/others/file_explorer \
Core/Src/lvgl/examples/others/font_manager \
Core/Src/lvgl/examples/others/fragment \
Core/Src/lvgl/examples/others/gestures \
Core/Src/lvgl/examples/others/gridnav \
Core/Src/lvgl/examples/others/ime \
Core/Src/lvgl/examples/others/imgfont \
Core/Src/lvgl/examples/others/monkey \
Core/Src/lvgl/examples/others/observer \
Core/Src/lvgl/examples/others/snapshot \
Core/Src/lvgl/examples/others/translation \
Core/Src/lvgl/examples/others/xml \
Core/Src/lvgl/examples/porting \
Core/Src/lvgl/examples/porting/osal \
Core/Src/lvgl/examples/scroll \
Core/Src/lvgl/examples/styles \
Core/Src/lvgl/examples/widgets/animimg \
Core/Src/lvgl/examples/widgets/arc \
Core/Src/lvgl/examples/widgets/arclabel \
Core/Src/lvgl/examples/widgets/bar \
Core/Src/lvgl/examples/widgets/button \
Core/Src/lvgl/examples/widgets/buttonmatrix \
Core/Src/lvgl/examples/widgets/calendar \
Core/Src/lvgl/examples/widgets/canvas \
Core/Src/lvgl/examples/widgets/chart \
Core/Src/lvgl/examples/widgets/checkbox \
Core/Src/lvgl/examples/widgets/dropdown \
Core/Src/lvgl/examples/widgets/image \
Core/Src/lvgl/examples/widgets/imagebutton \
Core/Src/lvgl/examples/widgets/keyboard \
Core/Src/lvgl/examples/widgets/label \
Core/Src/lvgl/examples/widgets/led \
Core/Src/lvgl/examples/widgets/line \
Core/Src/lvgl/examples/widgets/list \
Core/Src/lvgl/examples/widgets/lottie \
Core/Src/lvgl/examples/widgets/menu \
Core/Src/lvgl/examples/widgets/msgbox \
Core/Src/lvgl/examples/widgets/obj \
Core/Src/lvgl/examples/widgets/roller \
Core/Src/lvgl/examples/widgets/scale \
Core/Src/lvgl/examples/widgets/slider \
Core/Src/lvgl/examples/widgets/span \
Core/Src/lvgl/examples/widgets/spinbox \
Core/Src/lvgl/examples/widgets/spinner \
Core/Src/lvgl/examples/widgets/switch \
Core/Src/lvgl/examples/widgets/table \
Core/Src/lvgl/examples/widgets/tabview \
Core/Src/lvgl/examples/widgets/textarea \
Core/Src/lvgl/examples/widgets/tileview \
Core/Src/lvgl/examples/widgets/win \
Core/Src/lvgl/src/core \
Core/Src/lvgl/src/display \
Core/Src/lvgl/src/draw/dma2d \
Core/Src/lvgl/src/draw/espressif/ppa \
Core/Src/lvgl/src/draw/eve \
Core/Src/lvgl/src/draw \
Core/Src/lvgl/src/draw/nema_gfx \
Core/Src/lvgl/src/draw/nxp/g2d \
Core/Src/lvgl/src/draw/nxp/pxp \
Core/Src/lvgl/src/draw/nxp/vglite \
Core/Src/lvgl/src/draw/opengles \
Core/Src/lvgl/src/draw/renesas/dave2d \
Core/Src/lvgl/src/draw/sdl \
Core/Src/lvgl/src/draw/sw/blend/helium \
Core/Src/lvgl/src/draw/sw/blend \
Core/Src/lvgl/src/draw/sw/blend/neon \
Core/Src/lvgl/src/draw/sw \
Core/Src/lvgl/src/draw/vg_lite \
Core/Src/lvgl/src/drivers/display/drm \
Core/Src/lvgl/src/drivers/display/fb \
Core/Src/lvgl/src/drivers/display/ft81x \
Core/Src/lvgl/src/drivers/display/ili9341 \
Core/Src/lvgl/src/drivers/display/lcd \
Core/Src/lvgl/src/drivers/display/nxp_elcdif \
Core/Src/lvgl/src/drivers/display/renesas_glcdc \
Core/Src/lvgl/src/drivers/display/st7735 \
Core/Src/lvgl/src/drivers/display/st7789 \
Core/Src/lvgl/src/drivers/display/st7796 \
Core/Src/lvgl/src/drivers/display/st_ltdc \
Core/Src/lvgl/src/drivers/draw/eve \
Core/Src/lvgl/src/drivers/evdev \
Core/Src/lvgl/src/drivers/glfw \
Core/Src/lvgl/src/drivers/libinput \
Core/Src/lvgl/src/drivers/nuttx \
Core/Src/lvgl/src/drivers/qnx \
Core/Src/lvgl/src/drivers/sdl \
Core/Src/lvgl/src/drivers/uefi \
Core/Src/lvgl/src/drivers/wayland \
Core/Src/lvgl/src/drivers/windows \
Core/Src/lvgl/src/drivers/x11 \
Core/Src/lvgl/src/font \
Core/Src/lvgl/src/indev \
Core/Src/lvgl/src/layouts/flex \
Core/Src/lvgl/src/layouts/grid \
Core/Src/lvgl/src/layouts \
Core/Src/lvgl/src/libs/FT800-FT813 \
Core/Src/lvgl/src/libs/barcode \
Core/Src/lvgl/src/libs/bin_decoder \
Core/Src/lvgl/src/libs/bmp \
Core/Src/lvgl/src/libs/expat \
Core/Src/lvgl/src/libs/ffmpeg \
Core/Src/lvgl/src/libs/freetype \
Core/Src/lvgl/src/libs/fsdrv \
Core/Src/lvgl/src/libs/gif \
Core/Src/lvgl/src/libs/libjpeg_turbo \
Core/Src/lvgl/src/libs/libpng \
Core/Src/lvgl/src/libs/lodepng \
Core/Src/lvgl/src/libs/lz4 \
Core/Src/lvgl/src/libs/qrcode \
Core/Src/lvgl/src/libs/rle \
Core/Src/lvgl/src/libs/rlottie \
Core/Src/lvgl/src/libs/svg \
Core/Src/lvgl/src/libs/tiny_ttf \
Core/Src/lvgl/src/libs/tjpgd \
Core/Src/lvgl/src \
Core/Src/lvgl/src/misc/cache/class \
Core/Src/lvgl/src/misc/cache/instance \
Core/Src/lvgl/src/misc/cache \
Core/Src/lvgl/src/misc \
Core/Src/lvgl/src/osal \
Core/Src/lvgl/src/others/file_explorer \
Core/Src/lvgl/src/others/font_manager \
Core/Src/lvgl/src/others/fragment \
Core/Src/lvgl/src/others/gridnav \
Core/Src/lvgl/src/others/ime \
Core/Src/lvgl/src/others/imgfont \
Core/Src/lvgl/src/others/monkey \
Core/Src/lvgl/src/others/observer \
Core/Src/lvgl/src/others/snapshot \
Core/Src/lvgl/src/others/sysmon \
Core/Src/lvgl/src/others/test \
Core/Src/lvgl/src/others/translation \
Core/Src/lvgl/src/others/vg_lite_tvg \
Core/Src/lvgl/src/others/xml \
Core/Src/lvgl/src/others/xml/parsers \
Core/Src/lvgl/src/stdlib/builtin \
Core/Src/lvgl/src/stdlib/clib \
Core/Src/lvgl/src/stdlib \
Core/Src/lvgl/src/stdlib/micropython \
Core/Src/lvgl/src/stdlib/rtthread \
Core/Src/lvgl/src/stdlib/uefi \
Core/Src/lvgl/src/themes/default \
Core/Src/lvgl/src/themes \
Core/Src/lvgl/src/themes/mono \
Core/Src/lvgl/src/themes/simple \
Core/Src/lvgl/src/tick \
Core/Src/lvgl/src/widgets/3dtexture \
Core/Src/lvgl/src/widgets/animimage \
Core/Src/lvgl/src/widgets/arc \
Core/Src/lvgl/src/widgets/arclabel \
Core/Src/lvgl/src/widgets/bar \
Core/Src/lvgl/src/widgets/button \
Core/Src/lvgl/src/widgets/buttonmatrix \
Core/Src/lvgl/src/widgets/calendar \
Core/Src/lvgl/src/widgets/canvas \
Core/Src/lvgl/src/widgets/chart \
Core/Src/lvgl/src/widgets/checkbox \
Core/Src/lvgl/src/widgets/dropdown \
Core/Src/lvgl/src/widgets/image \
Core/Src/lvgl/src/widgets/imagebutton \
Core/Src/lvgl/src/widgets/keyboard \
Core/Src/lvgl/src/widgets/label \
Core/Src/lvgl/src/widgets/led \
Core/Src/lvgl/src/widgets/line \
Core/Src/lvgl/src/widgets/list \
Core/Src/lvgl/src/widgets/lottie \
Core/Src/lvgl/src/widgets/menu \
Core/Src/lvgl/src/widgets/msgbox \
Core/Src/lvgl/src/widgets/objx_templ \
Core/Src/lvgl/src/widgets/property \
Core/Src/lvgl/src/widgets/roller \
Core/Src/lvgl/src/widgets/scale \
Core/Src/lvgl/src/widgets/slider \
Core/Src/lvgl/src/widgets/span \
Core/Src/lvgl/src/widgets/spinbox \
Core/Src/lvgl/src/widgets/spinner \
Core/Src/lvgl/src/widgets/switch \
Core/Src/lvgl/src/widgets/table \
Core/Src/lvgl/src/widgets/tabview \
Core/Src/lvgl/src/widgets/textarea \
Core/Src/lvgl/src/widgets/tileview \
Core/Src/lvgl/src/widgets/win \
Core/Src/lvgl/tests/makefiles \
Core/Src/lvgl/tests/makefiles_uefi \
Core/Src/lvgl/tests/src \
Core/Src/lvgl/tests/src/test_assets \
Core/Src/lvgl/tests/src/test_cases \
Core/Src/lvgl/tests/src/test_cases/cache \
Core/Src/lvgl/tests/src/test_cases/draw \
Core/Src/lvgl/tests/src/test_cases/libs \
Core/Src/lvgl/tests/src/test_cases/widgets \
Core/Src/lvgl/tests/src/test_cases/xml \
Core/Src/lvgl/tests/src/test_cases_perf \
Core/Src/lvgl/tests/src/test_libs/rnd_unicodes \
Core/Src/lvgl/tests/src/test_libs/rnd_unicodes/rnd_unicodes/src \
Core/Src/lvgl/tests/test_images/stride_align1/LZ4 \
Core/Src/lvgl/tests/test_images/stride_align1/RLE \
Core/Src/lvgl/tests/test_images/stride_align1/UNCOMPRESSED \
Core/Src/lvgl/tests/test_images/stride_align64/LZ4 \
Core/Src/lvgl/tests/test_images/stride_align64/RLE \
Core/Src/lvgl/tests/test_images/stride_align64/UNCOMPRESSED \
Core/Src/lvgl/tests/unity \
Core/Startup \
Drivers/STM32F1xx_HAL_Driver/Src \
FATFS/App \
FATFS/Target \
Middlewares/Third_Party/FatFs/src \
Middlewares/Third_Party/FatFs/src/option \

